create table if not exists public.contabilidad_cuentas (
  id uuid primary key default gen_random_uuid(),
  codigo text not null unique,
  nombre text not null,
  tipo text not null,
  subtipo text null,
  cuenta_padre_id uuid null references public.contabilidad_cuentas(id),
  imputable boolean not null default true,
  activa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contabilidad_cuentas_tipo_check
    check (tipo in ('ACTIVO', 'PASIVO', 'PATRIMONIO_NETO', 'INGRESO', 'EGRESO', 'ORDEN'))
);

create index if not exists contabilidad_cuentas_codigo_idx
  on public.contabilidad_cuentas (codigo);

create index if not exists contabilidad_cuentas_tipo_idx
  on public.contabilidad_cuentas (tipo);

create index if not exists contabilidad_cuentas_activa_idx
  on public.contabilidad_cuentas (activa);

create table if not exists public.contabilidad_asientos (
  id uuid primary key default gen_random_uuid(),
  fecha date not null,
  numero bigint generated by default as identity,
  concepto text not null,
  origen text not null,
  origen_id uuid null,
  sede_id uuid null references public.sedes(id),
  estado text not null default 'borrador',
  created_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contabilidad_asientos_estado_check
    check (estado in ('borrador', 'confirmado', 'anulado')),
  constraint contabilidad_asientos_origen_check
    check (origen in ('manual', 'ingreso', 'egreso', 'banco', 'arca_invoice', 'orden_pago', 'ajuste'))
);

create index if not exists contabilidad_asientos_fecha_idx
  on public.contabilidad_asientos (fecha);

create index if not exists contabilidad_asientos_origen_idx
  on public.contabilidad_asientos (origen);

create index if not exists contabilidad_asientos_origen_id_idx
  on public.contabilidad_asientos (origen_id);

create index if not exists contabilidad_asientos_sede_id_idx
  on public.contabilidad_asientos (sede_id);

create index if not exists contabilidad_asientos_estado_idx
  on public.contabilidad_asientos (estado);

create table if not exists public.contabilidad_asiento_lineas (
  id uuid primary key default gen_random_uuid(),
  asiento_id uuid not null references public.contabilidad_asientos(id) on delete cascade,
  cuenta_id uuid not null references public.contabilidad_cuentas(id),
  descripcion text null,
  debe numeric(14,2) not null default 0,
  haber numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  constraint contabilidad_asiento_lineas_debe_check
    check (debe >= 0),
  constraint contabilidad_asiento_lineas_haber_check
    check (haber >= 0),
  constraint contabilidad_asiento_lineas_un_lado_check
    check (
      (debe > 0 and haber = 0)
      or
      (haber > 0 and debe = 0)
    )
);

create index if not exists contabilidad_asiento_lineas_asiento_id_idx
  on public.contabilidad_asiento_lineas (asiento_id);

create index if not exists contabilidad_asiento_lineas_cuenta_id_idx
  on public.contabilidad_asiento_lineas (cuenta_id);

alter table public.contabilidad_cuentas enable row level security;
alter table public.contabilidad_asientos enable row level security;
alter table public.contabilidad_asiento_lineas enable row level security;

drop policy if exists "contabilidad_cuentas_select_authenticated" on public.contabilidad_cuentas;
create policy "contabilidad_cuentas_select_authenticated"
  on public.contabilidad_cuentas
  for select
  using (auth.role() = 'authenticated');

drop policy if exists "contabilidad_cuentas_insert_authenticated" on public.contabilidad_cuentas;
create policy "contabilidad_cuentas_insert_authenticated"
  on public.contabilidad_cuentas
  for insert
  with check (auth.role() = 'authenticated');

drop policy if exists "contabilidad_cuentas_update_authenticated" on public.contabilidad_cuentas;
create policy "contabilidad_cuentas_update_authenticated"
  on public.contabilidad_cuentas
  for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "contabilidad_cuentas_delete_authenticated" on public.contabilidad_cuentas;
create policy "contabilidad_cuentas_delete_authenticated"
  on public.contabilidad_cuentas
  for delete
  using (auth.role() = 'authenticated');

drop policy if exists "contabilidad_asientos_select_authenticated" on public.contabilidad_asientos;
create policy "contabilidad_asientos_select_authenticated"
  on public.contabilidad_asientos
  for select
  using (auth.role() = 'authenticated');

drop policy if exists "contabilidad_asientos_insert_authenticated" on public.contabilidad_asientos;
create policy "contabilidad_asientos_insert_authenticated"
  on public.contabilidad_asientos
  for insert
  with check (auth.role() = 'authenticated');

drop policy if exists "contabilidad_asientos_update_authenticated" on public.contabilidad_asientos;
create policy "contabilidad_asientos_update_authenticated"
  on public.contabilidad_asientos
  for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "contabilidad_asientos_delete_authenticated" on public.contabilidad_asientos;
create policy "contabilidad_asientos_delete_authenticated"
  on public.contabilidad_asientos
  for delete
  using (auth.role() = 'authenticated');

drop policy if exists "contabilidad_asiento_lineas_select_authenticated" on public.contabilidad_asiento_lineas;
create policy "contabilidad_asiento_lineas_select_authenticated"
  on public.contabilidad_asiento_lineas
  for select
  using (auth.role() = 'authenticated');

drop policy if exists "contabilidad_asiento_lineas_insert_authenticated" on public.contabilidad_asiento_lineas;
create policy "contabilidad_asiento_lineas_insert_authenticated"
  on public.contabilidad_asiento_lineas
  for insert
  with check (auth.role() = 'authenticated');

drop policy if exists "contabilidad_asiento_lineas_update_authenticated" on public.contabilidad_asiento_lineas;
create policy "contabilidad_asiento_lineas_update_authenticated"
  on public.contabilidad_asiento_lineas
  for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "contabilidad_asiento_lineas_delete_authenticated" on public.contabilidad_asiento_lineas;
create policy "contabilidad_asiento_lineas_delete_authenticated"
  on public.contabilidad_asiento_lineas
  for delete
  using (auth.role() = 'authenticated');

insert into public.contabilidad_cuentas (codigo, nombre, tipo)
values
  ('1.1.01', 'Caja', 'ACTIVO'),
  ('1.1.02', 'Bancos', 'ACTIVO'),
  ('1.1.03', 'Clientes', 'ACTIVO'),
  ('1.1.04', 'Cuentas por cobrar', 'ACTIVO'),
  ('2.1.01', 'Proveedores', 'PASIVO'),
  ('2.1.02', 'IVA debito fiscal', 'PASIVO'),
  ('2.1.03', 'IVA credito fiscal', 'PASIVO'),
  ('2.1.04', 'Cuentas por pagar', 'PASIVO'),
  ('3.1.01', 'Capital', 'PATRIMONIO_NETO'),
  ('3.1.02', 'Resultados acumulados', 'PATRIMONIO_NETO'),
  ('4.1.01', 'Ventas servicios medicos', 'INGRESO'),
  ('4.1.02', 'Otros ingresos', 'INGRESO'),
  ('5.1.01', 'Compras', 'EGRESO'),
  ('5.1.02', 'Gastos administrativos', 'EGRESO'),
  ('5.1.03', 'Honorarios', 'EGRESO'),
  ('5.1.04', 'Servicios', 'EGRESO'),
  ('5.1.05', 'Impuestos y tasas', 'EGRESO'),
  ('5.1.06', 'Otros egresos', 'EGRESO')
on conflict (codigo) do nothing;
