create table if not exists public.ordenes_pago (
  id uuid primary key default gen_random_uuid(),
  fecha date not null default current_date,
  numero bigint generated by default as identity,
  proveedor text not null,
  proveedor_cuit text null,
  sociedad text null,
  sede_id uuid null references public.sedes(id),
  concepto text null,
  medio_pago text null,
  cuenta_pago text null,
  importe_total numeric(14,2) not null default 0,
  estado text not null default 'borrador',
  observaciones text null,
  created_by uuid null,
  approved_by uuid null,
  paid_by uuid null,
  approved_at timestamptz null,
  paid_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ordenes_pago_estado_check
    check (estado in ('borrador', 'aprobada', 'pagada', 'anulada'))
);

create index if not exists ordenes_pago_fecha_idx
  on public.ordenes_pago (fecha);

create index if not exists ordenes_pago_proveedor_idx
  on public.ordenes_pago (proveedor);

create index if not exists ordenes_pago_proveedor_cuit_idx
  on public.ordenes_pago (proveedor_cuit);

create index if not exists ordenes_pago_sede_id_idx
  on public.ordenes_pago (sede_id);

create index if not exists ordenes_pago_estado_idx
  on public.ordenes_pago (estado);

create table if not exists public.orden_pago_items (
  id uuid primary key default gen_random_uuid(),
  orden_pago_id uuid not null references public.ordenes_pago(id) on delete cascade,
  egreso_id uuid not null references public.egresos(id),
  descripcion text null,
  importe numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  constraint orden_pago_items_importe_check check (importe >= 0)
);

create index if not exists orden_pago_items_orden_pago_id_idx
  on public.orden_pago_items (orden_pago_id);

create index if not exists orden_pago_items_egreso_id_idx
  on public.orden_pago_items (egreso_id);

create unique index if not exists idx_orden_pago_items_egreso_activo
  on public.orden_pago_items (egreso_id)
  where egreso_id is not null;

alter table public.ordenes_pago enable row level security;
alter table public.orden_pago_items enable row level security;

drop policy if exists "ordenes_pago_select_authenticated" on public.ordenes_pago;
create policy "ordenes_pago_select_authenticated"
  on public.ordenes_pago
  for select
  to authenticated
  using (auth.role() = 'authenticated');

drop policy if exists "ordenes_pago_insert_authenticated" on public.ordenes_pago;
create policy "ordenes_pago_insert_authenticated"
  on public.ordenes_pago
  for insert
  to authenticated
  with check (auth.role() = 'authenticated');

drop policy if exists "ordenes_pago_update_authenticated" on public.ordenes_pago;
create policy "ordenes_pago_update_authenticated"
  on public.ordenes_pago
  for update
  to authenticated
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "ordenes_pago_delete_authenticated" on public.ordenes_pago;
create policy "ordenes_pago_delete_authenticated"
  on public.ordenes_pago
  for delete
  to authenticated
  using (auth.role() = 'authenticated');

drop policy if exists "orden_pago_items_select_authenticated" on public.orden_pago_items;
create policy "orden_pago_items_select_authenticated"
  on public.orden_pago_items
  for select
  to authenticated
  using (auth.role() = 'authenticated');

drop policy if exists "orden_pago_items_insert_authenticated" on public.orden_pago_items;
create policy "orden_pago_items_insert_authenticated"
  on public.orden_pago_items
  for insert
  to authenticated
  with check (auth.role() = 'authenticated');

drop policy if exists "orden_pago_items_update_authenticated" on public.orden_pago_items;
create policy "orden_pago_items_update_authenticated"
  on public.orden_pago_items
  for update
  to authenticated
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "orden_pago_items_delete_authenticated" on public.orden_pago_items;
create policy "orden_pago_items_delete_authenticated"
  on public.orden_pago_items
  for delete
  to authenticated
  using (auth.role() = 'authenticated');

notify pgrst, 'reload schema';
